-- Legacy setup has been retired. Do not run the old snapshot policy again.
-- Existing installations: use supabase-migration-01.sql, verify migrated data,
-- then run supabase-migration-02-cutover.sql before deploying the API-based site.
